name: Build and Release

# This workflow requires permission set to write on:
# https://github.com/jacklehamster/hamster-run/settings/actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.create_release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          TAG_NAME="v1.0.${{ github.run_number }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git $TAG_NAME

      - name: Check if Release Exists
        id: check_release
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = releases.find(r => r.tag_name === process.env.TAG_NAME);
            if (release) {
              fs.appendFileSync(process.env.GITHUB_OUTPUT, `release_exists=true\n`);
              fs.appendFileSync(process.env.GITHUB_OUTPUT, `upload_url=${release.upload_url}\n`);
            } else {
              fs.appendFileSync(process.env.GITHUB_OUTPUT, `release_exists=false\n`);
            }

      - name: Create Release
        id: create_release
        if: steps.check_release.outputs.release_exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

  build-windows:
    runs-on: windows-latest
    needs: create_release
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Windows
        run: bun run build:win

      - name: Zip Build Artifact
        run: |
          powershell Compress-Archive -Path dist/hamster_run.exe -DestinationPath dist/windows-build.zip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/windows-build.zip
          asset_name: windows-build.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    needs: create_release
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build macOS
        run: bun run build:mac

      - name: Upload macOS Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh release upload ${{ needs.create_release.outputs.tag_name }} dist/hamster-run-1.0.0-universal-mac.zip --clobber

  build-linux:
    runs-on: ubuntu-latest
    needs: create_release
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build linux
        run: bun run build:linux

      - name: Upload linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/hamster-run-1.0.0.zip
          asset_name: linux-build.zip
          asset_content_type: application/zip
